### ISSUE TITLE
Need To Know More About The Web Pixel Or App Pixel

### ISSUE THREAD

**Issue by adventuretocode** [BTrain137/Shopify-help#82]
looking more detail example in web pixel.

1. how to migrate script_tag or theme app extension  to the webpixel ?
2. it is still beta versions ?
3. why we want to move the assest or theme app block to the app pxiel ?
4. app pixel is loading into the iframe so it can access the main root document ?
5. for Pixel and ga4 type app can be work fine ?
6. for if any store has using the custom or third part app for the "add to cart" feature still the add_to_cart happend in pixel ?
7. can I write any js code in the js files ?
8. what are limitation for web pixel ?
9. Facebook pixel can be work with app pixel ?
10. how much time take build then deploy to reflect in store side.

**Comment by BTrain137** [comment]
Hey @adventuretocode,

Sorry, I didn't see this. I'll can only answer a few of these questions, as I have to research the rest of the questions. 

2. I believe its out now. 
3. Shopify is trying to keep standard with all the pixel code in their pixel API.
     A. The reason is because pixel code has certain 'events' such as add to cart etc.
4.  You are correct, no you cannot access the Root dom elements. 
     A. I was able to do a custom event and pass custom information through the pixel.
     B. I'll try to make example codes out of this.
 5. They should..... work fine.
 6. Yes, you can log add to cart using the pixel.
 7. I believe so
 8. Its an iframe, it very specific to its event. So if you are monitoring more than 1 event, you'll need to create each pixel
 9. Yes, I saw an example code of this. I'll try to include it in this repo. Its somewhere....
 10. I haven't done this myself, but I am if its already built its pretty quick.
